# ios/Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '17.0'

prepare_react_native_project!

target 'MyMapApp' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true
  )

  # MapLibre Native iOS matching @maplibre/maplibre-react-native@11.0.0-alpha.5
  pod 'MapLibre', '~> 6.4'
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false
  )
end
